"""ZeroNexus 500 Feature Master Specification Registry.

Defines every single feature from 1 to 500 as REQUIRED.
Provides lookup, category filtering, keyword searching and metadata binding.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional


@dataclass(frozen=True)
class MasterFeature:
    """500 大師特性單項描述資料結構。"""
    id: int
    category: str
    name: str
    description: str
    service_domain: str


# 完整 500 項官方需求清單字典
_RAW_500_FEATURES = [
    # AI / INTELLIGENCE (1-100)
    (1, "AI / INTELLIGENCE", "AI 對話人格切換", "切換不同風格之 AI 角色與說話基底", "ai_studio"),
    (2, "AI / INTELLIGENCE", "AI 自訂人格建立器", "支援使用者自訂專屬 AI 人格提示詞與特徵", "ai_studio"),
    (3, "AI / INTELLIGENCE", "AI Guild 專屬人格", "伺服器級別全域預設 AI 人格設定", "ai_studio"),
    (4, "AI / INTELLIGENCE", "AI Channel 專屬人格", "個別文字頻道綁定之專屬 AI 人格", "ai_studio"),
    (5, "AI / INTELLIGENCE", "AI User 專屬偏好", "使用者跨頻道個人專屬 AI 回應偏好", "ai_studio"),
    (6, "AI / INTELLIGENCE", "AI 對話上下文管理", "動態滑動視窗與對話歷史權重維護", "ai_studio"),
    (7, "AI / INTELLIGENCE", "AI 長對話自動壓縮", "對話長度接近上限時自動語意壓縮", "ai_studio"),
    (8, "AI / INTELLIGENCE", "AI 長對話摘要", "定時提煉歷史核心對白與未解決問題", "ai_studio"),
    (9, "AI / INTELLIGENCE", "AI 對話主題偵測", "即時捕捉當前討論領域與話題切換", "ai_studio"),
    (10, "AI / INTELLIGENCE", "AI 意圖辨識", "深度辨識使用者提問之底層真實意圖", "ai_studio"),
    (11, "AI / INTELLIGENCE", "AI 自動工具選擇", "依據問題需求自主推薦合適工具鏈", "ai_studio"),
    (12, "AI / INTELLIGENCE", "AI Tool Calling", "向後端執行環境發起結構化工具調用", "ai_studio"),
    (13, "AI / INTELLIGENCE", "AI Tool Result 解釋", "以自然語言解釋工具輸出並萃取事實", "ai_studio"),
    (14, "AI / INTELLIGENCE", "AI 多模型路由", "動態在 Gemini, DeepSeek, Qwen 等模型間路由", "ai_studio"),
    (15, "AI / INTELLIGENCE", "AI Model Fallback", "單一模型故障或超額時無縫平滑降級", "ai_studio"),
    (16, "AI / INTELLIGENCE", "AI Model Health Check", "即時心跳檢測各模型端點可用狀態", "ai_studio"),
    (17, "AI / INTELLIGENCE", "AI Model Latency Tracking", "持續記錄並統計各端點響應延遲指標", "ai_studio"),
    (18, "AI / INTELLIGENCE", "AI Model Availability Detection", "端點配額與連線異常即時監控", "ai_studio"),
    (19, "AI / INTELLIGENCE", "AI Model Capability Detection", "模型視覺、工具與深思支援度識別", "ai_studio"),
    (20, "AI / INTELLIGENCE", "AI 自動選擇適合模型", "按任務複雜度動態指派旗艦或極速模型", "ai_studio"),
    (21, "AI / INTELLIGENCE", "AI 使用者模型偏好", "記憶使用者指定偏好調用之預設模型", "ai_studio"),
    (22, "AI / INTELLIGENCE", "AI 回覆重新生成", "不改變上下文重新採樣推演全新回覆", "ai_studio"),
    (23, "AI / INTELLIGENCE", "AI 回覆風格切換", "即時調整當次回應之修辭與口吻", "ai_studio"),
    (24, "AI / INTELLIGENCE", "AI 正式模式", "嚴謹官方公文與學術規格論述模式", "ai_studio"),
    (25, "AI / INTELLIGENCE", "AI 朋友模式", "熱情幽默、懂讀空氣的死黨聊天模式", "ai_studio"),
    (26, "AI / INTELLIGENCE", "AI 教師模式", "循序漸進、耐心的引導與教學解惑模式", "ai_studio"),
    (27, "AI / INTELLIGENCE", "AI 工程師模式", "聚焦效能、架構取捨與極致實用主義模式", "ai_studio"),
    (28, "AI / INTELLIGENCE", "AI Debug 模式", "深度堆疊追蹤、根本原因與修復驗證模式", "ai_studio"),
    (29, "AI / INTELLIGENCE", "AI Research 模式", "嚴密批判性辯證與文獻來源追蹤模式", "ai_studio"),
    (30, "AI / INTELLIGENCE", "AI Assistant 模式", "高效率條列要點與直接行動方案模式", "ai_studio"),
    (31, "AI / INTELLIGENCE", "AI Prompt Analyzer", "剖析提示詞結構、清晰度與隱含限制", "ai_studio"),
    (32, "AI / INTELLIGENCE", "AI Prompt Optimizer", "重構提示詞以提升大模型遵循度與品質", "ai_studio"),
    (33, "AI / INTELLIGENCE", "AI Prompt Tester", "模擬不同邊界測試案例檢驗提示詞表現", "ai_studio"),
    (34, "AI / INTELLIGENCE", "AI Prompt Playground", "互動式參數與提示詞即時實驗沙盒", "ai_studio"),
    (35, "AI / INTELLIGENCE", "AI Response Analyzer", "評估模型回覆之結構完整性與條理性", "ai_studio"),
    (36, "AI / INTELLIGENCE", "AI Response Quality Feedback", "蒐集並記錄對話品質滿意度評分", "ai_studio"),
    (37, "AI / INTELLIGENCE", "AI Hallucination Warning", "針對無確鑿依據之內容主動標示警示", "ai_studio"),
    (38, "AI / INTELLIGENCE", "AI Uncertainty Detection", "辨識語意中之推測與不確定性標記", "ai_studio"),
    (39, "AI / INTELLIGENCE", "AI Source Awareness", "提示回答引用之底層知識與即時來源", "ai_studio"),
    (40, "AI / INTELLIGENCE", "AI Context Relevance Ranking", "上下文檢索片段相關性打分與排序", "ai_studio"),
    (41, "AI / INTELLIGENCE", "AI Automatic Context Selection", "自動篩選與當前問題最相關之歷史資訊", "ai_studio"),
    (42, "AI / INTELLIGENCE", "AI Conversation Topic Switching", "偵測並平滑過渡至全新討論命題", "ai_studio"),
    (43, "AI / INTELLIGENCE", "AI Conversation Thread Detection", "識別群聊中交錯的多個獨立話題線", "ai_studio"),
    (44, "AI / INTELLIGENCE", "AI Conversation Summary", "結構化總結討論脈絡與共識觀點", "ai_studio"),
    (45, "AI / INTELLIGENCE", "AI Conversation Action Extraction", "萃取對話中指派或承諾之後續行動項目", "ai_studio"),
    (46, "AI / INTELLIGENCE", "AI Automatic Todo Extraction", "自動將言談中的交辦任務轉為待辦項", "ai_studio"),
    (47, "AI / INTELLIGENCE", "AI Automatic Reminder Extraction", "自動識別對話中的未來時間並提示提醒", "ai_studio"),
    (48, "AI / INTELLIGENCE", "AI Automatic Decision Extraction", "提取群體討論後最終拍板之定案決策", "ai_studio"),
    (49, "AI / INTELLIGENCE", "AI Automatic Question Extraction", "梳理討論中尚待解答之懸置問題", "ai_studio"),
    (50, "AI / INTELLIGENCE", "AI Automatic Important Message Detection", "智慧標記頻道內具關鍵價值之里程碑訊息", "ai_studio"),
    (51, "AI / INTELLIGENCE", "AI Message Classification", "依主題、優先度與性質將訊息多維分類", "ai_studio"),
    (52, "AI / INTELLIGENCE", "AI Message Intent Classification", "精確劃分對話屬於問答、閒聊或操作委託", "ai_studio"),
    (53, "AI / INTELLIGENCE", "AI Language Detection", "辨識訊息輸入所使用之語言類型", "ai_studio"),
    (54, "AI / INTELLIGENCE", "AI Translation", "高品質多語系即時在地化翻譯", "ai_studio"),
    (55, "AI / INTELLIGENCE", "AI Tone Detection", "分析發言者當前語調偏好與情緒色彩", "ai_studio"),
    (56, "AI / INTELLIGENCE", "AI Sentiment Analysis", "情感傾向正向/負向/中立數值分析", "ai_studio"),
    (57, "AI / INTELLIGENCE", "AI Emotion Context Detection", "偵測成員之挫折、喜悅或焦慮情緒上下文", "ai_studio"),
    (58, "AI / INTELLIGENCE", "AI Writing Assistant", "各類文案、散文與敘事起草助手", "ai_studio"),
    (59, "AI / INTELLIGENCE", "AI Rewrite Assistant", "在保留核心原意下換句話說多樣重寫", "ai_studio"),
    (60, "AI / INTELLIGENCE", "AI Grammar Assistant", "繁體中文語病修飾與錯別字修正", "ai_studio"),
    (61, "AI / INTELLIGENCE", "AI Summarization", "長篇論述高保真提煉摘要", "ai_studio"),
    (62, "AI / INTELLIGENCE", "AI Expansion", "擴寫綱要為細節充實之完整論述", "ai_studio"),
    (63, "AI / INTELLIGENCE", "AI Shortening", "精簡篇幅並保留最關鍵要點", "ai_studio"),
    (64, "AI / INTELLIGENCE", "AI Formalization", "將口語轉化為商業與官方正式規格文書", "ai_studio"),
    (65, "AI / INTELLIGENCE", "AI Casualization", "將硬邦邦文章轉化為生動親切網路用語", "ai_studio"),
    (66, "AI / INTELLIGENCE", "AI Announcement Generator", "專業社群重要公告草稿撰寫器", "ai_studio"),
    (67, "AI / INTELLIGENCE", "AI Discord Message Generator", "專為 Discord 平台閱讀優化之格式訊息", "ai_studio"),
    (68, "AI / INTELLIGENCE", "AI Embed Content Generator", "符合 Embed 規範之無Markdown標題內容", "ai_studio"),
    (69, "AI / INTELLIGENCE", "AI Documentation Generator", "軟體架構與使用教學文件生成器", "ai_studio"),
    (70, "AI / INTELLIGENCE", "AI FAQ Generator", "依據歷史討論自動歸納常見問答集", "ai_studio"),
    (71, "AI / INTELLIGENCE", "AI FAQ Answering", "直接自 FAQ 索引最佳答案並精確回覆", "ai_studio"),
    (72, "AI / INTELLIGENCE", "AI Knowledge Extraction", "從混亂對話中萃取結構化事實與概念", "ai_studio"),
    (73, "AI / INTELLIGENCE", "AI Structured Data Extraction", "提取實體名詞、數值與屬性對應關係", "ai_studio"),
    (74, "AI / INTELLIGENCE", "AI Table Generation", "將混亂數據轉換為美觀排版表格", "ai_studio"),
    (75, "AI / INTELLIGENCE", "AI JSON Generation", "輸出嚴格符合 Schema 之 JSON 格式字串", "ai_studio"),
    (76, "AI / INTELLIGENCE", "AI JSON Repair", "自動修復不完整或語法損壞之 JSON 結構", "ai_studio"),
    (77, "AI / INTELLIGENCE", "AI YAML Generation", "產生嚴謹縮排之 YAML 配置檔案內容", "ai_studio"),
    (78, "AI / INTELLIGENCE", "AI Markdown Generation", "輸出符合 GFM 規範之結構化 Markdown", "ai_studio"),
    (79, "AI / INTELLIGENCE", "AI Regex Generation", "依文字匹配需求生成精確正規表達式", "ai_studio"),
    (80, "AI / INTELLIGENCE", "AI SQL Generation", "依業務需求直譯為高相容性 SQL 查詢", "ai_studio"),
    (81, "AI / INTELLIGENCE", "AI SQL Explanation", "逐步逐行解析複雜 SQL 語句之執行邏輯", "ai_studio"),
    (82, "AI / INTELLIGENCE", "AI API Explanation", "解讀 REST/GraphQL API 端點與參數規格", "ai_studio"),
    (83, "AI / INTELLIGENCE", "AI API Documentation Generator", "依代碼產生 OpenAPI/Swagger 規格文件", "ai_studio"),
    (84, "AI / INTELLIGENCE", "AI Code Generation", "高品質多語言演算法與實作代碼生成", "ai_studio"),
    (85, "AI / INTELLIGENCE", "AI Code Review", "審核代碼安全漏洞、反模式與重構建議", "ai_studio"),
    (86, "AI / INTELLIGENCE", "AI Code Debugging", "分析錯誤現象並提出精準修復代碼補丁", "ai_studio"),
    (87, "AI / INTELLIGENCE", "AI Stack Trace Analysis", "解析錯誤堆疊追蹤定位第一事發檔案與行號", "ai_studio"),
    (88, "AI / INTELLIGENCE", "AI Error Explanation", "用人話清楚說明罕見技術報錯之根本由來", "ai_studio"),
    (89, "AI / INTELLIGENCE", "AI Log Analysis", "分析海量系統日誌快速鎖定異常事件鏈", "ai_studio"),
    (90, "AI / INTELLIGENCE", "AI Git Diff Analysis", "分析變更差異並摘要影響範圍與架構變動", "ai_studio"),
    (91, "AI / INTELLIGENCE", "AI Commit Message Generation", "產生符合 Conventional Commits 規範之訊息", "ai_studio"),
    (92, "AI / INTELLIGENCE", "AI Changelog Generation", "依提交日誌生成易讀的版本更新公告", "ai_studio"),
    (93, "AI / INTELLIGENCE", "AI README Generation", "自動編撰專案導覽、安裝指引與核心功能", "ai_studio"),
    (94, "AI / INTELLIGENCE", "AI Architecture Analysis", "剖析系統分層架構、瓶頸點與解耦建議", "ai_studio"),
    (95, "AI / INTELLIGENCE", "AI Project Planning", "將宏大專案目標轉化為里程碑與排程計畫", "ai_studio"),
    (96, "AI / INTELLIGENCE", "AI Task Breakdown", "將大型複雜需求原子化拆解為細項工作", "ai_studio"),
    (97, "AI / INTELLIGENCE", "AI Technical Specification Generator", "撰寫技術規格白皮書與介面定義文件", "ai_studio"),
    (98, "AI / INTELLIGENCE", "AI Test Case Generator", "針對模組設計正常與邊界極值測試案例", "ai_studio"),
    (99, "AI / INTELLIGENCE", "AI Bug Report Generator", "產生標準化重現步驟與環境描述之 Bug 報告", "ai_studio"),
    (100, "AI / INTELLIGENCE", "AI Development Assistant", "全方位軟體生命週期智慧協同開發助手", "ai_studio"),

    # AI MEMORY (101-140)
    (101, "AI MEMORY", "User Short-Term Memory", "使用者即時會話滑動短期工作記憶", "memory"),
    (102, "AI MEMORY", "User Long-Term Memory", "跨會話持久化保存之個人長期習慣與偏好", "memory"),
    (103, "AI MEMORY", "Guild Memory", "伺服器共享記憶庫（社群規範與專有文化）", "memory"),
    (104, "AI MEMORY", "Channel Memory", "特定文字頻道內之專案或主題上下文記憶", "memory"),
    (105, "AI MEMORY", "Conversation Memory", "當前對話串專屬之連續互動記憶", "memory"),
    (106, "AI MEMORY", "Memory Search", "支援關鍵字與語意相似度檢索歷史記憶", "memory"),
    (107, "AI MEMORY", "Memory Categories", "依偏好、事實、規則與待辦將記憶結構分類", "memory"),
    (108, "AI MEMORY", "Memory Importance Scoring", "記憶重要性打分，關鍵資訊優先持久保存", "memory"),
    (109, "AI MEMORY", "Memory Relevance Scoring", "檢索時計算與當前問題之關聯度權重", "memory"),
    (110, "AI MEMORY", "Memory Expiration", "為臨時時效性記憶設定存活時間 (TTL)", "memory"),
    (111, "AI MEMORY", "Memory Automatic Cleanup", "自動排程清理過期與無效之歷史記憶片段", "memory"),
    (112, "AI MEMORY", "Memory Conflict Detection", "偵測新偏好與既有記憶相牴觸之衝突點", "memory"),
    (113, "AI MEMORY", "Memory Update Detection", "識別資訊更迭並自主覆寫更新舊版記憶", "memory"),
    (114, "AI MEMORY", "Memory Duplicate Detection", "防止完全相同之冗餘記憶重複寫入資料庫", "memory"),
    (115, "AI MEMORY", "Memory Compression", "多條相關細碎記憶合併為高度精煉之事實", "memory"),
    (116, "AI MEMORY", "Memory Summarization", "全域記憶長程摘要與生活足跡概覽", "memory"),
    (117, "AI MEMORY", "User Memory Viewer", "提供使用者查看自身已被記錄之記憶面板", "memory"),
    (118, "AI MEMORY", "User Memory Editor", "支援使用者手動修改錯誤或陳舊之記憶條目", "memory"),
    (119, "AI MEMORY", "User Memory Delete", "提供刪除特定或全部個人記憶之完全掌控權", "memory"),
    (120, "AI MEMORY", "User Memory Export", "將個人歷史記憶導出為標準 JSON 文件", "memory"),
    (121, "AI MEMORY", "User Memory Import", "將外部 JSON 記憶備份匯入至系統中", "memory"),
    (122, "AI MEMORY", "Guild Memory Viewer", "管理員專屬之伺服器記憶檢視介面", "memory"),
    (123, "AI MEMORY", "Guild Memory Management", "伺服器層級記憶之新增、修改與封存控制", "memory"),
    (124, "AI MEMORY", "AI Automatic Memory Candidate Detection", "AI 自動從對話捕捉具儲存價值之個人特質", "memory"),
    (125, "AI MEMORY", "Explicit Memory Requests", "精確響應「請記住...」等明確記憶儲存指令", "memory"),
    (126, "AI MEMORY", "Memory Confirmation System", "儲存重要敏感記憶前主動向使用者發送確認", "memory"),
    (127, "AI MEMORY", "Memory Privacy Controls", "多層級隱私設定，杜絕未經授權之記憶讀取", "memory"),
    (128, "AI MEMORY", "Memory Scope Control", "定義記憶適用於個人、伺服器或全域邊界", "memory"),
    (129, "AI MEMORY", "Channel Memory Isolation", "嚴格確保各頻道記憶不發生非預期 cross-talk", "memory"),
    (130, "AI MEMORY", "Guild Memory Isolation", "伺服器間記憶完全實體隔離，保障商業隱私", "memory"),
    (131, "AI MEMORY", "User Memory Isolation", "不同使用者間個人偏好數據絕對獨立保護", "memory"),
    (132, "AI MEMORY", "Memory Audit Log", "記錄記憶讀取與寫入之時間、呼叫源與權限", "memory"),
    (133, "AI MEMORY", "Memory Usage Statistics", "統計記憶總容量、條目數與命中命中率", "memory"),
    (134, "AI MEMORY", "Memory Relevance Ranking", "高維度動態排序篩選出最高相關度前 N 條", "memory"),
    (135, "AI MEMORY", "Memory Retrieval Context", "將檢索出之事實安全格式化並組裝至 Context", "memory"),
    (136, "AI MEMORY", "Memory Citation", "回答時主動標註「依據您先前提到的...」記憶來源", "memory"),
    (137, "AI MEMORY", "Memory Source Tracking", "追溯記憶最早由哪一則對話或檔案所建立", "memory"),
    (138, "AI MEMORY", "Memory Timestamp Tracking", "記錄記憶產生與最後一次被命中的時間戳", "memory"),
    (139, "AI MEMORY", "Memory Confidence Score", "記憶可信度打分，區分推測與確定事實", "memory"),
    (140, "AI MEMORY", "Memory Relationship Mapping", "建立記憶實體間的關聯拓撲連結網絡", "memory"),

    # AI KNOWLEDGE (141-175)
    (141, "AI KNOWLEDGE", "AI Knowledge Base", "全域通識與技術核心知識庫", "knowledge"),
    (142, "AI KNOWLEDGE", "Guild Knowledge Base", "伺服器專屬知識庫與組織規則資料集", "knowledge"),
    (143, "AI KNOWLEDGE", "Channel Knowledge Base", "頻道特定專案與工作流程專屬知識", "knowledge"),
    (144, "AI KNOWLEDGE", "Personal Knowledge Base", "個人筆記與自訂常備知識文庫", "knowledge"),
    (145, "AI KNOWLEDGE", "Document Knowledge Base", "上傳之 PDF、Markdown 與文字手冊知識庫", "knowledge"),
    (146, "AI KNOWLEDGE", "URL Knowledge Base", "爬取網頁內容萃取而來之網路知識文庫", "knowledge"),
    (147, "AI KNOWLEDGE", "FAQ Knowledge Base", "社群高頻問題與官方標準答案資料庫", "knowledge"),
    (148, "AI KNOWLEDGE", "Knowledge Search", "多維度知識全文檢索器", "knowledge"),
    (149, "AI KNOWLEDGE", "Semantic Knowledge Search", "語意向量距離最近鄰知識檢索", "knowledge"),
    (150, "AI KNOWLEDGE", "Keyword Knowledge Search", "BM25 關鍵字布林精準匹配搜尋", "knowledge"),
    (151, "AI KNOWLEDGE", "Knowledge Ranking", "多路檢索綜合重新評分與排序 (Re-ranking)", "knowledge"),
    (152, "AI KNOWLEDGE", "Knowledge Categories", "樹狀分類體系階層化組織知識資產", "knowledge"),
    (153, "AI KNOWLEDGE", "Knowledge Tags", "多標籤標記與交集過濾檢索系統", "knowledge"),
    (154, "AI KNOWLEDGE", "Knowledge Versioning", "知識條目歷史變更版本紀錄與回滾", "knowledge"),
    (155, "AI KNOWLEDGE", "Knowledge Source Tracking", "追蹤每條知識項目的最初來源文件或網址", "knowledge"),
    (156, "AI KNOWLEDGE", "Knowledge Update Detection", "監聽來源文件變動並提示知識項更新", "knowledge"),
    (157, "AI KNOWLEDGE", "Knowledge Expiration Detection", "定時檢驗過時條目並標示需人工校閱", "knowledge"),
    (158, "AI KNOWLEDGE", "Knowledge Conflict Detection", "檢測多個來源間陳述相衝突之知識謬誤", "knowledge"),
    (159, "AI KNOWLEDGE", "Knowledge Duplicate Detection", "辨識語意重複知識並提供合併建議", "knowledge"),
    (160, "AI KNOWLEDGE", "Knowledge Import", "批次匯入外部結構化知識數據", "knowledge"),
    (161, "AI KNOWLEDGE", "Knowledge Export", "完整導出知識庫為 Markdown 或 JSON", "knowledge"),
    (162, "AI KNOWLEDGE", "Knowledge Document Upload", "支援透過 Discord 附件上傳文字檔案建庫", "knowledge"),
    (163, "AI KNOWLEDGE", "Knowledge URL Import", "輸入網址由背景抓取並自動轉為知識條目", "knowledge"),
    (164, "AI KNOWLEDGE", "Knowledge Text Import", "直接貼上長篇純文字由 AI 智慧切片建庫", "knowledge"),
    (165, "AI KNOWLEDGE", "Knowledge Markdown Import", "解析 Markdown 標題層級自動構建知識樹", "knowledge"),
    (166, "AI KNOWLEDGE", "Knowledge PDF Processing", "提取 PDF 文字內容並清洗格式入庫", "knowledge"),
    (167, "AI KNOWLEDGE", "Knowledge FAQ Builder", "引導式互動建立問答對 (Q&A Pairs)", "knowledge"),
    (168, "AI KNOWLEDGE", "AI Document Question Answering", "精確根據知識庫文件段落回答使用者諮詢", "knowledge"),
    (169, "AI KNOWLEDGE", "AI Knowledge Summarization", "將知識庫某一領域資產提煉為核心綱要", "knowledge"),
    (170, "AI KNOWLEDGE", "AI Knowledge Extraction", "自主從聊天紀錄萃取有價值之知識條目", "knowledge"),
    (171, "AI KNOWLEDGE", "AI Knowledge Classification", "將新知識條目自動分類至最適合之目錄", "knowledge"),
    (172, "AI KNOWLEDGE", "AI Knowledge Linking", "分析概念間之因果與從屬關聯並建立連結", "knowledge"),
    (173, "AI KNOWLEDGE", "AI Knowledge Graph", "以圖結構儲存實體關係並支援多跳推論", "knowledge"),
    (174, "AI KNOWLEDGE", "Knowledge Confidence", "依來源權威度為每項知識標註置信分數", "knowledge"),
    (175, "AI KNOWLEDGE", "Knowledge Usage Analytics", "統計各條知識被引用率與解答有效性", "knowledge"),

    # AI AGENT / REASONING (176-200)
    (176, "AI AGENT / REASONING", "AI Task Planner", "高階任務規劃器，將終極目標轉化為步驟", "agent"),
    (177, "AI AGENT / REASONING", "AI Multi-Step Task Execution", "自動依序排程執行多步驟複合任務", "agent"),
    (178, "AI AGENT / REASONING", "AI Task State Tracking", "即時追蹤當前任務之等待、運行或完成狀態", "agent"),
    (179, "AI AGENT / REASONING", "AI Task Progress Tracking", "即時回報當前步驟與百分比完成進度", "agent"),
    (180, "AI AGENT / REASONING", "AI Task Cancellation", "支援使用者中途安全中斷或終止長時間任務", "agent"),
    (181, "AI AGENT / REASONING", "AI Task Retry", "子步驟遇暫態失敗時自動重試機制", "agent"),
    (182, "AI AGENT / REASONING", "AI Task Failure Recovery", "任務遭遇未預期例外時之自動降級自癒方案", "agent"),
    (183, "AI AGENT / REASONING", "AI Tool Selection Reasoning", "輸出為何挑選特定工具之邏輯理由思考鏈", "agent"),
    (184, "AI AGENT / REASONING", "AI Tool Dependency Detection", "分析工具間之前置輸入相依性與順序", "agent"),
    (185, "AI AGENT / REASONING", "AI Tool Result Validation", "嚴格校驗工具回傳之資料型別與有效性", "agent"),
    (186, "AI AGENT / REASONING", "AI Result Consistency Check", "檢查多個子步驟輸出是否彼此矛盾", "agent"),
    (187, "AI AGENT / REASONING", "AI Multi-Source Information Synthesis", "整合多個 API 與檢索結果形成綜合報告", "agent"),
    (188, "AI AGENT / REASONING", "AI Context Prioritization", "動態賦予各資訊源優先權限以防 Context 溢位", "agent"),
    (189, "AI AGENT / REASONING", "AI Relevant History Selection", "精準挑選最相關歷史軌跡作為推演依據", "agent"),
    (190, "AI AGENT / REASONING", "AI Task Decomposition", "將複雜問題遞迴拆解為單一職責子任務", "agent"),
    (191, "AI AGENT / REASONING", "AI Subtask Management", "並行或串行排程各子任務並彙整產出", "agent"),
    (192, "AI AGENT / REASONING", "AI Action Plan Generation", "產生包含預估耗時與風險之具體行動清單", "agent"),
    (193, "AI AGENT / REASONING", "AI Decision Tree Generation", "依條件分支展開可視化決策樹策略", "agent"),
    (194, "AI AGENT / REASONING", "AI Workflow Generation", "自動生成自動化工作流定義模型", "agent"),
    (195, "AI AGENT / REASONING", "AI Workflow Explanation", "以通俗語言逐步向使用者解說工作流邏輯", "agent"),
    (196, "AI AGENT / REASONING", "AI Workflow Validation", "靜態驗證工作流有無無窮迴圈或未封閉分支", "agent"),
    (197, "AI AGENT / REASONING", "AI Workflow Simulation", "在虛擬沙盒中模擬執行工作流確認安全性", "agent"),
    (198, "AI AGENT / REASONING", "AI Automation Suggestion", "主動觀察社群重複操作並建議自動化方案", "agent"),
    (199, "AI AGENT / REASONING", "AI Automation Builder", "透過對話互動引導建立全自動化機器人動作", "agent"),
    (200, "AI AGENT / REASONING", "AI Natural Language Command Interpreter", "將口語自然語言直譯為精準斜線指令與參數", "agent"),

    # DISCORD CORE (201-225)
    (201, "DISCORD CORE", "Welcome System", "新成員加入時之智慧自動歡迎流程", "discord_core"),
    (202, "DISCORD CORE", "Leave Notification", "成員離群時之溫馨送別與紀錄通知", "discord_core"),
    (203, "DISCORD CORE", "Custom Welcome Card", "客製化排版與美觀之歡迎 Embed 卡片", "discord_core"),
    (204, "DISCORD CORE", "Custom Leave Card", "客製化排版之成員離開資訊卡片", "discord_core"),
    (205, "DISCORD CORE", "Member Join Statistics", "記錄並統計每日/每週成員加入速率", "discord_core"),
    (206, "DISCORD CORE", "Member Leave Statistics", "記錄並分析退群數據與流失時機", "discord_core"),
    (207, "DISCORD CORE", "Member Activity Statistics", "成員發言頻率、在線時長與活躍度度量", "discord_core"),
    (208, "DISCORD CORE", "Channel Activity Statistics", "統計各頻道訊息總量與互動熱度分佈", "discord_core"),
    (209, "DISCORD CORE", "Guild Activity Statistics", "全伺服器綜合活躍指標彙整統計", "discord_core"),
    (210, "DISCORD CORE", "Message Statistics", "精確記錄訊息發布量、編輯與刪除統計", "discord_core"),
    (211, "DISCORD CORE", "Daily Chat Statistics", "每日發言曲線與高峰時段分析", "discord_core"),
    (212, "DISCORD CORE", "Weekly Chat Statistics", "每週聊天活躍趨勢與波動報告", "discord_core"),
    (213, "DISCORD CORE", "Monthly Chat Statistics", "月度發言總量與長期參與度走勢", "discord_core"),
    (214, "DISCORD CORE", "Activity Leaderboard", "伺服器綜合活躍度前十名排行榜", "discord_core"),
    (215, "DISCORD CORE", "Message Leaderboard", "發言訊息總量英雄榜", "discord_core"),
    (216, "DISCORD CORE", "Voice Activity Leaderboard", "語音頻道掛機與通話時數排行榜", "discord_core"),
    (217, "DISCORD CORE", "Command Leaderboard", "機器人指令調用最活躍使用者排名", "discord_core"),
    (218, "DISCORD CORE", "AI Usage Leaderboard", "與 AI 助手深度交流次數排行榜", "discord_core"),
    (219, "DISCORD CORE", "Guild Growth Analytics", "伺服器人口成長率與淨增長趨勢分析", "discord_core"),
    (220, "DISCORD CORE", "Member Retention Analytics", "新成員第 7 天/第 30 天留存率分析", "discord_core"),
    (221, "DISCORD CORE", "New Member Activity Analytics", "新進成員首日發言與破冰行為分析", "discord_core"),
    (222, "DISCORD CORE", "Automatic Guild Report", "系統全自動排程生成之社群健康總覽", "discord_core"),
    (223, "DISCORD CORE", "Daily Guild Report", "每日社群日報與精華重點速讀", "discord_core"),
    (224, "DISCORD CORE", "Weekly Guild Report", "每週社群營運週報與趨勢預警", "discord_core"),
    (225, "DISCORD CORE", "Monthly Guild Report", "月度完整社群指標、活躍度與成長報告", "discord_core"),

    # DISCORD INTERACTION (226-250)
    (226, "DISCORD INTERACTION", "Interactive Menu Builder", "動態多級下拉選單產生器", "interaction"),
    (227, "DISCORD INTERACTION", "Button Action System", "支援持久化 Components V2 按鈕觸發動作", "interaction"),
    (228, "DISCORD INTERACTION", "Select Menu System", "單選與多選下拉選單事件派送系統", "interaction"),
    (229, "DISCORD INTERACTION", "Modal Form System", "彈出式多欄位彈窗輸入表單系統", "interaction"),
    (230, "DISCORD INTERACTION", "Interactive Embed Builder", "即時可視化調整 Embed 邊框色與欄位建構器", "interaction"),
    (231, "DISCORD INTERACTION", "Embed Template System", "預置多種官方主題範本卡片庫", "interaction"),
    (232, "DISCORD INTERACTION", "Dynamic Button Messages", "隨狀態動態變更按鈕樣式與停用狀態", "interaction"),
    (233, "DISCORD INTERACTION", "Interactive Message Workflow", "透過連續按鈕引導使用者完成多步操作", "interaction"),
    (234, "DISCORD INTERACTION", "Multi-Step Forms", "支援跨頁連續填寫之多步驟表單", "interaction"),
    (235, "DISCORD INTERACTION", "Form Validation", "輸入即時型別、長度與合法性防禦校驗", "interaction"),
    (236, "DISCORD INTERACTION", "Form Result Processing", "表單提交結果自動寫入資料庫與觸發流程", "interaction"),
    (237, "DISCORD INTERACTION", "Form Result Notification", "表單送出後即時向指定頻道發布通知", "interaction"),
    (238, "DISCORD INTERACTION", "Context Menu Tools", "整合滑鼠右鍵上下文選單工具集", "interaction"),
    (239, "DISCORD INTERACTION", "User Context Commands", "右鍵點選成員快速查詢檔案或執行管理", "interaction"),
    (240, "DISCORD INTERACTION", "Message Context Commands", "右鍵點選訊息發起 AI 分析或加入待辦", "interaction"),
    (241, "DISCORD INTERACTION", "Thread Automation", "討論串生命週期全自動化管理", "interaction"),
    (242, "DISCORD INTERACTION", "Automatic Thread Creation", "偵測特定標籤或關鍵字自動建立子討論串", "interaction"),
    (243, "DISCORD INTERACTION", "Automatic Thread Archiving", "長久未活動之討論串自動封存以保整潔", "interaction"),
    (244, "DISCORD INTERACTION", "Thread Activity Tracking", "監控各子討論串發言量與解決狀態", "interaction"),
    (245, "DISCORD INTERACTION", "Interactive Help System", "分類可分頁之互動式說明導覽介面", "interaction"),
    (246, "DISCORD INTERACTION", "Dynamic Help Menu", "隨權限與模組載入狀態動態顯示可用指令", "interaction"),
    (247, "DISCORD INTERACTION", "Command Discovery", "引導式新手指令探索與推薦列表", "interaction"),
    (248, "DISCORD INTERACTION", "Command Search", "輸入關鍵字即時搜尋匹配之功能與指令", "interaction"),
    (249, "DISCORD INTERACTION", "Command Suggestions", "打錯字時以模糊演算法自動建議正確指令", "interaction"),
    (250, "DISCORD INTERACTION", "Natural Language Command Search", "用口語描述目的自動尋找並執行對應指令", "interaction"),

    # COMMUNITY (251-275)
    (251, "COMMUNITY", "Poll System", "標準社群多選項投票系統", "community"),
    (252, "COMMUNITY", "Anonymous Poll", "隱匿投票者身分之匿名投票保密機制", "community"),
    (253, "COMMUNITY", "Live Poll Results", "即時票數比例動態長條圖卡片更新", "community"),
    (254, "COMMUNITY", "Scheduled Poll", "排程於特定時間自動開啟與結票之投票", "community"),
    (255, "COMMUNITY", "Multi-Choice Poll", "支援複選多個偏好選項之彈性投票", "community"),
    (256, "COMMUNITY", "Ranking Poll", "以偏好排序權重計分之高級投票", "community"),
    (257, "COMMUNITY", "Proposal System", "社群公共事務提案發起與立案流程", "community"),
    (258, "COMMUNITY", "Proposal Voting", "提案贊成/反對票決與門檻判定系統", "community"),
    (259, "COMMUNITY", "Proposal Discussion", "為每項提案自動開闢專屬討論串辯論", "community"),
    (260, "COMMUNITY", "Suggestion Box", "成員向伺服器管理群反饋點子之建議箱", "community"),
    (261, "COMMUNITY", "Anonymous Suggestion Box", "保護隱私之完全匿名意見反饋管道", "community"),
    (262, "COMMUNITY", "AI Suggestion Summarization", "AI 自動歸納匯總每週建議核心重點", "community"),
    (263, "COMMUNITY", "AI Suggestion Classification", "AI 自動將建議按功能、規則或優化分類", "community"),
    (264, "COMMUNITY", "Duplicate Suggestion Detection", "智慧辨識與歷史建議高度相似之重複反饋", "community"),
    (265, "COMMUNITY", "Community Announcement Scheduler", "預約排程未來發布社群重要活動公告", "community"),
    (266, "COMMUNITY", "Announcement Draft Assistant", "AI 輔助優化公告用詞與美化排版", "community"),
    (267, "COMMUNITY", "Announcement Translation", "一鍵將重要公告翻譯為多語系廣播", "community"),
    (268, "COMMUNITY", "Announcement Read Statistics", "統計點擊查看與已讀成員數據", "community"),
    (269, "COMMUNITY", "Announcement Reaction Statistics", "統計公告各 Emoji 反應分佈與回饋", "community"),
    (270, "COMMUNITY", "Community Event Manager", "社群線上聚會與競賽活動管理中樞", "community"),
    (271, "COMMUNITY", "Community Calendar", "伺服器近期活動日程表與日曆檢視", "community"),
    (272, "COMMUNITY", "Event Registration", "成員一鍵點擊報名參加活動之名額系統", "community"),
    (273, "COMMUNITY", "Event Reminder", "活動開始前 15 分鐘自動私訊或標註提醒", "community"),
    (274, "COMMUNITY", "Event Attendance Tracking", "活動當天即時簽到與出席名單點名", "community"),
    (275, "COMMUNITY", "Event Summary", "活動結束後自動產生精彩剪影與紀錄總結", "community"),

    # SOCIAL / PROFILE (276-295)
    (276, "SOCIAL / PROFILE", "User Activity Profile", "個人多維度社群互動履歷檔案", "social_profile"),
    (277, "SOCIAL / PROFILE", "User Chat Statistics", "個人發言總字數、平均長度與互動熱度", "social_profile"),
    (278, "SOCIAL / PROFILE", "User Command Statistics", "個人最常使用之指令與調用累積次數", "social_profile"),
    (279, "SOCIAL / PROFILE", "User AI Statistics", "個人與 AI 助手對話輪數與生圖消費統計", "social_profile"),
    (280, "SOCIAL / PROFILE", "User Voice Statistics", "個人於語音包廂累積通話與開麥時長", "social_profile"),
    (281, "SOCIAL / PROFILE", "User XP System", "依發言與參與貢獻獲取經驗值之數值引擎", "social_profile"),
    (282, "SOCIAL / PROFILE", "User Level System", "經驗值累積升級解鎖專屬社群特權與身分", "social_profile"),
    (283, "SOCIAL / PROFILE", "Daily XP Missions", "每日登入發言與與 AI 對話獲取額外經驗任務", "social_profile"),
    (284, "SOCIAL / PROFILE", "Achievement System", "達成特定里程碑解鎖之榮譽成就徽章庫", "social_profile"),
    (285, "SOCIAL / PROFILE", "Title System", "佩戴於個人檔案之自訂稱號與頭銜系統", "social_profile"),
    (286, "SOCIAL / PROFILE", "Badge System", "展示於個人名片之特殊成就徽章陣容", "social_profile"),
    (287, "SOCIAL / PROFILE", "User Leaderboard", "全伺服器個人等級與經驗值霸榜排行榜", "social_profile"),
    (288, "SOCIAL / PROFILE", "Guild Leaderboard", "社群成員活躍貢獻綜合風雲榜", "social_profile"),
    (289, "SOCIAL / PROFILE", "Global Leaderboard", "跨伺服器 ZeroNexus 使用者全球榮譽榜", "social_profile"),
    (290, "SOCIAL / PROFILE", "Profile Card", "精美圖文排版之個人生涯檔案 Embed 名片", "social_profile"),
    (291, "SOCIAL / PROFILE", "Custom Profile Card", "自訂名片配色、簽名檔與展示成就", "social_profile"),
    (292, "SOCIAL / PROFILE", "User Activity Time Analysis", "分析個人每週最常在線與發言之黃金時段", "social_profile"),
    (293, "SOCIAL / PROFILE", "Favorite Channel Analysis", "統計個人最常發言與駐留之熱門頻道", "social_profile"),
    (294, "SOCIAL / PROFILE", "Favorite Command Analysis", "剖析個人最偏好調用之功能與服務偏好", "social_profile"),
    (295, "SOCIAL / PROFILE", "Personal Year Review", "年度個人足跡精彩回顧 (Year in Review)", "social_profile"),

    # AUTOMATION (296-330)
    (296, "AUTOMATION", "Scheduled Tasks", "單次指定未來精確時間執行之定時任務", "automation"),
    (297, "AUTOMATION", "Recurring Tasks", "以固定間隔時間重複循環執行之自動任務", "automation"),
    (298, "AUTOMATION", "Cron Tasks", "標準 5 欄位 Cron 表達式驅動之強大定時器", "automation"),
    (299, "AUTOMATION", "Automatic Messages", "定時向指定文字頻道發送預設內容訊息", "automation"),
    (300, "AUTOMATION", "Automatic Embeds", "定時動態產生並刷新狀態 Embed 訊息卡", "automation"),
    (301, "AUTOMATION", "Automatic Announcements", "排程定時廣播社群重大活動或提醒通知", "automation"),
    (302, "AUTOMATION", "Automatic Reminders", "到期自動標註特定成員或頻道之備忘提醒", "automation"),
    (303, "AUTOMATION", "Expired Message Cleanup", "定時自動清除指定頻道內之過期暫態訊息", "automation"),
    (304, "AUTOMATION", "Automatic Thread Creation", "符合條件自動為新訊息開闢專用子討論串", "automation"),
    (305, "AUTOMATION", "Automatic Channel Archiving", "長期無人說話之臨時頻道自動移動並封存", "automation"),
    (306, "AUTOMATION", "Automatic Role Assignment", "加入或達成成就自動發放對應身分組", "automation"),
    (307, "AUTOMATION", "Automatic Role Removal", "違規或期限到期自動收回特定身分組", "automation"),
    (308, "AUTOMATION", "Role Synchronization", "跨頻道或依據條件自動雙向同步身分組狀態", "automation"),
    (309, "AUTOMATION", "Automatic Welcome Workflow", "新人加入自動發送私訊指引並賦予預設身分", "automation"),
    (310, "AUTOMATION", "New Member Tutorial", "互動式新手教學引導任務流程", "automation"),
    (311, "AUTOMATION", "Event Reminder Automation", "全自動活動前置廣播與語音集結提醒", "automation"),
    (312, "AUTOMATION", "Birthday Reminder", "成員生日當天自動發布全群慶生祝賀卡片", "automation"),
    (313, "AUTOMATION", "Weekly Report Automation", "每週日晚間自動彙整生成社群運營週報", "automation"),
    (314, "AUTOMATION", "Conditional Automation", "若條件 A 成立則觸發執行動作 B 之邏輯引擎", "automation"),
    (315, "AUTOMATION", "Multi-Condition Trigger", "支援 AND、OR、NOT 複合布林條件判斷", "automation"),
    (316, "AUTOMATION", "Message Trigger", "接收到特定內容或格式訊息時觸發工作流", "automation"),
    (317, "AUTOMATION", "Reaction Trigger", "特定訊息被新增指定 Emoji 反應時觸發", "automation"),
    (318, "AUTOMATION", "Button Trigger", "使用者點擊特定互動按鈕時觸發自訂工作流", "automation"),
    (319, "AUTOMATION", "Role Trigger", "身分組被賦予或收回時觸發連帶更新流程", "automation"),
    (320, "AUTOMATION", "Member Join Trigger", "新成員踏入伺服器瞬間觸發鏈路", "automation"),
    (321, "AUTOMATION", "Member Leave Trigger", "成員離群時觸發權限註銷與資料歸檔", "automation"),
    (322, "AUTOMATION", "Keyword Trigger", "訊息包含指定敏感或重要關鍵字時觸發", "automation"),
    (323, "AUTOMATION", "AI Intent Trigger", "AI 識別出特定語意意圖時自主啟動工作流", "automation"),
    (324, "AUTOMATION", "Time Trigger", "精確到達特定世界標準時間時觸發事件", "automation"),
    (325, "AUTOMATION", "Webhook Trigger", "接收外部系統 HTTP POST Webhook 觸發動作", "automation"),
    (326, "AUTOMATION", "API Trigger", "內部或外部 REST API 呼叫發起之自動化", "automation"),
    (327, "AUTOMATION", "External Service Trigger", "整合 GitHub、Notion 或其他第三方事件觸發", "automation"),
    (328, "AUTOMATION", "Workflow Builder", "可視化自訂工作流編輯器與組裝工具", "automation"),
    (329, "AUTOMATION", "Workflow Debugger", "工作流單步除錯器，檢視變數傳遞與日誌", "automation"),
    (330, "AUTOMATION", "Workflow Execution History", "工作流完整調用歷史、耗時與成功率紀錄", "automation"),

    # MODERATION / SAFETY (331-350)
    (331, "MODERATION / SAFETY", "Spam Detection", "高頻垃圾訊息與商業廣告即時偵測攔截", "moderation"),
    (332, "MODERATION / SAFETY", "Flood Detection", "短時間暴力刷屏洪水攻擊防禦防護", "moderation"),
    (333, "MODERATION / SAFETY", "Duplicate Message Detection", "連續發送完全相同文字之重複刷屏偵測", "moderation"),
    (334, "MODERATION / SAFETY", "Invite Link Detection", "未經許可之外部 Discord 邀請碼攔截與刪除", "moderation"),
    (335, "MODERATION / SAFETY", "Malicious URL Detection", "可疑釣魚網站、假 Nitro 與空投惡意網址偵測", "moderation"),
    (336, "MODERATION / SAFETY", "Suspicious Message Detection", "結合正則與啟發式模型辨識可疑詐欺私訊", "moderation"),
    (337, "MODERATION / SAFETY", "Raid Detection", "伺服器遭大量機器人突襲湧入防禦警報", "moderation"),
    (338, "MODERATION / SAFETY", "Raid Early Warning", "早期流量突增預警，提前發送告警通知", "moderation"),
    (339, "MODERATION / SAFETY", "Abnormal Join Rate Detection", "監控成員加入速率突增之異常行為分析", "moderation"),
    (340, "MODERATION / SAFETY", "Abnormal Message Rate Detection", "全服訊息吞吐量異常暴增警示分析", "moderation"),
    (341, "MODERATION / SAFETY", "Automatic Slowmode Recommendation", "當聊天室過熱時主動建議適當慢速冷卻時間", "moderation"),
    (342, "MODERATION / SAFETY", "Risk Report", "伺服器當前整體安全風險評分與弱點報告", "moderation"),
    (343, "MODERATION / SAFETY", "Moderation Dashboard", "管理員專屬之違規審核與案件監控儀表板", "moderation"),
    (344, "MODERATION / SAFETY", "Moderation Log", "詳盡記錄所有禁言、警告與踢除之稽核日誌", "moderation"),
    (345, "MODERATION / SAFETY", "Moderation Case System", "具備案件編號、處置理由與執行者之案件庫", "moderation"),
    (346, "MODERATION / SAFETY", "Warning Case System", "階梯式警告累積計點與自動處置處罰系統", "moderation"),
    (347, "MODERATION / SAFETY", "Appeal Ticket", "被處置成員專用之申訴工單與審查流程", "moderation"),
    (348, "MODERATION / SAFETY", "Automatic Moderation Record", "機器人處置違規自動即時歸檔與快照備份", "moderation"),
    (349, "MODERATION / SAFETY", "AI Moderation Assistant", "AI 語意理解輔助分析惡意意圖與謾罵", "moderation"),
    (350, "MODERATION / SAFETY", "Moderation Audit Analyzer", "定期分析審核處分分布檢視管轄是否公允", "moderation"),

    # DEVELOPER TOOLS (351-395)
    (351, "DEVELOPER TOOLS", "JSON Formatter", "美化縮排與彩色高亮 JSON 資料", "dev_tools"),
    (352, "DEVELOPER TOOLS", "JSON Validator", "語法檢查與報錯定位不合法 JSON 字元", "dev_tools"),
    (353, "DEVELOPER TOOLS", "JSON Minifier", "去除空白與換行壓縮 JSON 減小傳輸體積", "dev_tools"),
    (354, "DEVELOPER TOOLS", "YAML Validator", "嚴格驗證 YAML 語法結構與縮排正確性", "dev_tools"),
    (355, "DEVELOPER TOOLS", "YAML Formatter", "標準化格式化 YAML 配置內容", "dev_tools"),
    (356, "DEVELOPER TOOLS", "XML Formatter", "標籤成對匹配與階層美化 XML 文件", "dev_tools"),
    (357, "DEVELOPER TOOLS", "Base64 Encoder", "將純文字或資料轉換為 Base64 字串", "dev_tools"),
    (358, "DEVELOPER TOOLS", "Base64 Decoder", "將 Base64 編碼解碼還原為明文字元", "dev_tools"),
    (359, "DEVELOPER TOOLS", "URL Encoder", "百分比編碼 (Percent-encoding) 特殊網址字元", "dev_tools"),
    (360, "DEVELOPER TOOLS", "URL Decoder", "還原已編碼之網址參數文字", "dev_tools"),
    (361, "DEVELOPER TOOLS", "URL Parser", "精確解析 URL 之協議、主機、路徑與查詢參數", "dev_tools"),
    (362, "DEVELOPER TOOLS", "UUID Generator", "生成高熵標準 UUID v4 唯一辨識碼", "dev_tools"),
    (363, "DEVELOPER TOOLS", "Hash Generator", "計算輸入資料之 MD5 與 SHA 雜湊值", "dev_tools"),
    (364, "DEVELOPER TOOLS", "SHA Generator", "計算密碼級 SHA-256 與 SHA-512 校驗值", "dev_tools"),
    (365, "DEVELOPER TOOLS", "Regex Tester", "即時測試正規表達式之匹配分組結果", "dev_tools"),
    (366, "DEVELOPER TOOLS", "Regex Explainer", "逐段解析並以自然語言解釋正則表達式語意", "dev_tools"),
    (367, "DEVELOPER TOOLS", "Cron Generator", "直覺引導式產生正確格式之 Cron 時間表達式", "dev_tools"),
    (368, "DEVELOPER TOOLS", "Timestamp Converter", "毫秒/秒級時間戳與 ISO 日期時間互相轉換", "dev_tools"),
    (369, "DEVELOPER TOOLS", "Unix Timestamp Generator", "即時取得當前 Unix Epoch 時間戳與 Discord 格式", "dev_tools"),
    (370, "DEVELOPER TOOLS", "Color Converter", "HEX, RGB, HSL 與整數色彩代碼互相轉換", "dev_tools"),
    (371, "DEVELOPER TOOLS", "Code Formatter", "常見程式語言代碼風格美化對齊", "dev_tools"),
    (372, "DEVELOPER TOOLS", "Code Language Detector", "分析代碼片段語法自動辨識所屬程式語言", "dev_tools"),
    (373, "DEVELOPER TOOLS", "Stack Trace Analyzer", "分析崩潰堆疊追蹤定位錯誤發生模組", "dev_tools"),
    (374, "DEVELOPER TOOLS", "Error Message Analyzer", "解析異常報錯代碼並提供排查思路", "dev_tools"),
    (375, "DEVELOPER TOOLS", "Log Formatter", "美化純文字伺服器日誌並解析時間戳", "dev_tools"),
    (376, "DEVELOPER TOOLS", "Log Analyzer", "過濾日誌中之 WARN 與 ERROR 嚴重等級紀錄", "dev_tools"),
    (377, "DEVELOPER TOOLS", "HTTP Request Builder", "互動式組裝 HTTP 請求方法、標頭與 Payload", "dev_tools"),
    (378, "DEVELOPER TOOLS", "API Request Tester", "非同步發送 API 測試請求並回傳狀態與耗時", "dev_tools"),
    (379, "DEVELOPER TOOLS", "REST API Explorer", "探索公開 RESTful API 端點與資料結構", "dev_tools"),
    (380, "DEVELOPER TOOLS", "Webhook Tester", "向指定 Webhook 發送測試酬載檢驗回饋", "dev_tools"),
    (381, "DEVELOPER TOOLS", "Webhook Generator", "產生 Discord 或第三方相容格式之 Webhook 酬載", "dev_tools"),
    (382, "DEVELOPER TOOLS", "JWT Decoder", "解碼 JWT Token 之 Header 與 Payload 資訊", "dev_tools"),
    (383, "DEVELOPER TOOLS", "JWT Inspector", "檢視 Token 過期時間 (exp) 與簽發方 (iss)", "dev_tools"),
    (384, "DEVELOPER TOOLS", "SQL Formatter", "關鍵字大寫與標準化縮排 SQL 查詢指令", "dev_tools"),
    (385, "DEVELOPER TOOLS", "SQL Validator", "檢查 SQL 語法結構之關鍵字與括號完整性", "dev_tools"),
    (386, "DEVELOPER TOOLS", "SQL Query Explainer", "分析 SQL 查詢執行計畫與索引命中邏輯", "dev_tools"),
    (387, "DEVELOPER TOOLS", "Git Diff Analyzer", "解析 Unified Diff 語法顯示增刪行數", "dev_tools"),
    (388, "DEVELOPER TOOLS", "Git Commit Generator", "依據變更內容產生規範化 Git Commit 說明", "dev_tools"),
    (389, "DEVELOPER TOOLS", "Git Branch Naming Helper", "依照功能、修復或重構推薦語意化分支名稱", "dev_tools"),
    (390, "DEVELOPER TOOLS", "Semantic Version Generator", "依據破壞性變更推薦 SemVer 版本跳號", "dev_tools"),
    (391, "DEVELOPER TOOLS", "Changelog Generator", "彙整多次提交為精煉的發布變更日誌", "dev_tools"),
    (392, "DEVELOPER TOOLS", "README Generator", "產生包含架構、安裝與授權之開源 README", "dev_tools"),
    (393, "DEVELOPER TOOLS", "License Generator", "生成 MIT、Apache 2.0 或 GPL 標準開源授權書", "dev_tools"),
    (394, "DEVELOPER TOOLS", ".gitignore Generator", "依據指定開發語言生成標準 .gitignore 檔案", "dev_tools"),
    (395, "DEVELOPER TOOLS", "Text Diff Tool", "行對行比對兩段純文字內容並標示差異", "dev_tools"),

    # WEB / API (396-415)
    (396, "WEB / API", "Website HTTP Status", "查詢目標網站目前之 HTTP 回應狀態碼", "web_api"),
    (397, "WEB / API", "Website Latency Test", "測量目標網址之 TCP/HTTP 連線延遲毫秒", "web_api"),
    (398, "WEB / API", "Website Uptime Monitor", "持續追蹤網站運行時間與斷線紀錄", "web_api"),
    (399, "WEB / API", "SSL Certificate Check", "檢驗目標網域之 SSL/TLS 憑證簽發方與演算法", "web_api"),
    (400, "WEB / API", "SSL Expiration Reminder", "計算憑證剩餘天數並於到期前提前提醒", "web_api"),
    (401, "WEB / API", "DNS Lookup", "查詢網域名稱解析出之 A 記錄 IPv4 位址", "web_api"),
    (402, "WEB / API", "DNS Record Viewer", "檢視網域之 A, CNAME, MX, TXT 等完整記錄", "web_api"),
    (403, "WEB / API", "IP Information", "查詢指定 IP 位址之地理位置、ASN 與供應商", "web_api"),
    (404, "WEB / API", "Domain Information", "查詢網域名稱之註冊商、註冊時間與狀態", "web_api"),
    (405, "WEB / API", "HTTP Header Viewer", "檢驗目標網站伺服器回傳之完整 HTTP 標頭", "web_api"),
    (406, "WEB / API", "Redirect Chain Analyzer", "追蹤多次 301/302 轉址跳轉鏈之最終目標", "web_api"),
    (407, "WEB / API", "API Health Monitor", "定期對外部 API 進行探針健康檢查", "web_api"),
    (408, "WEB / API", "API Response Monitor", "監控 API 回傳資料格式是否符合預期 Schema", "web_api"),
    (409, "WEB / API", "API Latency Monitor", "繪製 API 響應時間趨勢並發布延遲警告", "web_api"),
    (410, "WEB / API", "API Error Rate Monitor", "統計 4xx 與 5xx 錯誤比例與突發高峰", "web_api"),
    (411, "WEB / API", "Webhook Monitor", "監控 Webhook 投遞成功率與重試次數", "web_api"),
    (412, "WEB / API", "URL Metadata Extractor", "自 HTML 原始碼提取標題、描述與圖示元數據", "web_api"),
    (413, "WEB / API", "OpenGraph Preview", "抓取 og:title, og:image 等社群分享卡片預覽", "web_api"),
    (414, "WEB / API", "Website Title Extractor", "快速抓取任意合法網址之 <title> 網頁標題", "web_api"),
    (415, "WEB / API", "Website Change Detector", "比對網頁純文字雜湊值偵測內容是否有重大更動", "web_api"),

    # SYSTEM / BOT INTELLIGENCE (416-435)
    (416, "SYSTEM / BOT INTELLIGENCE", "ZeroNexus System Status", "機器人總體運行指標與運算核心狀態概覽", "system_monitor"),
    (417, "SYSTEM / BOT INTELLIGENCE", "CPU Monitor", "即時 CPU 使用率百分比與多核心負載監控", "system_monitor"),
    (418, "SYSTEM / BOT INTELLIGENCE", "RAM Monitor", "實體記憶體總量、已用量與百分比監控", "system_monitor"),
    (419, "SYSTEM / BOT INTELLIGENCE", "Disk Monitor", "主硬碟分割區剩餘容量與磁碟 I/O 監控", "system_monitor"),
    (420, "SYSTEM / BOT INTELLIGENCE", "Network Monitor", "機器人進出網路頻寬流量傳輸統計", "system_monitor"),
    (421, "SYSTEM / BOT INTELLIGENCE", "Process Monitor", "機器人當前 Python 行程 PID 與 RSS 佔用", "system_monitor"),
    (422, "SYSTEM / BOT INTELLIGENCE", "Python Runtime Information", "Python 執行時版本、編譯器與底層作業系統", "system_monitor"),
    (423, "SYSTEM / BOT INTELLIGENCE", "Dependency Version Checker", "檢驗 discord.py, sqlalchemy, httpx 等核心版本", "system_monitor"),
    (424, "SYSTEM / BOT INTELLIGENCE", "Bot Uptime", "機器人自上次啟動以來的累積連續運行時長", "system_monitor"),
    (425, "SYSTEM / BOT INTELLIGENCE", "Bot Restart History", "記錄機器人重啟時間點、退出代碼與原因", "system_monitor"),
    (426, "SYSTEM / BOT INTELLIGENCE", "Bot Error Counter", "統計運行期間捕捉到之未處理異常累積總數", "system_monitor"),
    (427, "SYSTEM / BOT INTELLIGENCE", "Bot Exception Analyzer", "自動歸納近期拋出最高頻率之錯誤堆疊類型", "system_monitor"),
    (428, "SYSTEM / BOT INTELLIGENCE", "Bot Latency Monitor", "即時 WebSocket 心跳延遲 (Ping) 監控", "system_monitor"),
    (429, "SYSTEM / BOT INTELLIGENCE", "Discord Gateway Monitor", "監控 Discord Gateway 連線、Resumed 與重連事件", "system_monitor"),
    (430, "SYSTEM / BOT INTELLIGENCE", "API Dependency Monitor", "監控 Gemini, OpenRouter 等外部依賴可用性", "system_monitor"),
    (431, "SYSTEM / BOT INTELLIGENCE", "Service Health Dashboard", "內部所有 Cog 與 Service 之健康狀態總看板", "system_monitor"),
    (432, "SYSTEM / BOT INTELLIGENCE", "Service Dependency Graph", "可視化內部模組與外掛間之相依性拓撲圖", "system_monitor"),
    (433, "SYSTEM / BOT INTELLIGENCE", "System Alert", "當硬體負載過高或端點故障時向管理員告警", "system_monitor"),
    (434, "SYSTEM / BOT INTELLIGENCE", "Automatic Health Report", "每日定時巡檢並產出系統維運健康檢測報表", "system_monitor"),
    (435, "SYSTEM / BOT INTELLIGENCE", "Diagnostic Snapshot", "一鍵匯出包含環境、硬體與日誌之診斷快照", "system_monitor"),

    # ANALYTICS (436-455)
    (436, "ANALYTICS", "Guild Analytics", "伺服器全維度營運與活躍度深度分析", "analytics"),
    (437, "ANALYTICS", "Message Analytics", "發言長度、Emoji 使用率與附件類型分佈", "analytics"),
    (438, "ANALYTICS", "Command Analytics", "各項斜線指令調用頻次與熱門排行分析", "analytics"),
    (439, "ANALYTICS", "AI Analytics", "AI Token 消費量、生圖數與對話熱度指標", "analytics"),
    (440, "ANALYTICS", "Member Analytics", "活躍成員比例、沉默成員與沉睡用戶分析", "analytics"),
    (441, "ANALYTICS", "Channel Analytics", "各頻道互動流動率與活躍時間段分佈", "analytics"),
    (442, "ANALYTICS", "Voice Analytics", "語音頻道各時段同時在線人數與掛機分佈", "analytics"),
    (443, "ANALYTICS", "Activity Heatmap", "24x7 小時社群發言強度視覺化熱圖", "analytics"),
    (444, "ANALYTICS", "Hourly Activity Graph", "每日每小時互動量波動折線趨勢圖", "analytics"),
    (445, "ANALYTICS", "Daily Activity Graph", "過去 30 天每日互動量長條統計圖", "analytics"),
    (446, "ANALYTICS", "Weekly Activity Graph", "週與週之間社群參與度對比分析圖", "analytics"),
    (447, "ANALYTICS", "Monthly Activity Graph", "年度各月份發言量與用戶活躍對比圖", "analytics"),
    (448, "ANALYTICS", "Command Trend Graph", "熱門功能調用次數隨時間上升/下降趨勢", "analytics"),
    (449, "ANALYTICS", "AI Usage Trend Graph", "AI 助手依賴度與對話時長成長曲線", "analytics"),
    (450, "ANALYTICS", "Member Growth Graph", "伺服器累積成員與每日淨加入走勢圖", "analytics"),
    (451, "ANALYTICS", "Retention Graph", "不同梯次成員加入後之 30 天留存漏斗圖", "analytics"),
    (452, "ANALYTICS", "Engagement Score", "結合發言、按鈕與語音之綜合社群參與評分", "analytics"),
    (453, "ANALYTICS", "Activity Anomaly Detection", "演算法偵測突發異常流量或斷崖式冷清預警", "analytics"),
    (454, "ANALYTICS", "Analytics Export", "導出完整多維度分析指標為 CSV 或 JSON", "analytics"),
    (455, "ANALYTICS", "Automated Analytics Report", "定時產出圖文並茂之社群多維度綜合分析報表", "analytics"),

    # REAL-TIME INFORMATION (456-475)
    (456, "REAL-TIME INFORMATION", "Real-Time Weather", "臺灣各縣市及全球城市即時觀測氣象", "realtime_info"),
    (457, "REAL-TIME INFORMATION", "Weather Forecast", "未來一週高低溫、天氣現象與天氣趨勢預報", "realtime_info"),
    (458, "REAL-TIME INFORMATION", "Multi-Location Weather", "一次同時比對多個目標城市之當前天氣概況", "realtime_info"),
    (459, "REAL-TIME INFORMATION", "Rain Forecast", "36 小時逐 3 小時降雨機率與出門攜帶雨具建議", "realtime_info"),
    (460, "REAL-TIME INFORMATION", "Feels-Like Temperature", "綜合相對濕度與風速計算之精確人體體感溫度", "realtime_info"),
    (461, "REAL-TIME INFORMATION", "UV Information", "紫外線指數 (UVI) 級別與防曬係數防護建議", "realtime_info"),
    (462, "REAL-TIME INFORMATION", "Air Quality", "環境部官方空氣品質指標 (AQI) 即時回報", "realtime_info"),
    (463, "REAL-TIME INFORMATION", "PM2.5 Information", "細懸浮微粒 (PM2.5) 濃度數值與健康防範提醒", "realtime_info"),
    (464, "REAL-TIME INFORMATION", "Earthquake Information", "中央氣象署最新顯著有感地震即時報告速報", "realtime_info"),
    (465, "REAL-TIME INFORMATION", "Earthquake History", "查詢臺灣周邊歷史強烈地震紀錄與震央分佈", "realtime_info"),
    (466, "REAL-TIME INFORMATION", "Weather Alerts", "大雨、豪雨、低溫、濃霧特報即時廣播", "realtime_info"),
    (467, "REAL-TIME INFORMATION", "Typhoon Information", "西北太平洋熱帶氣旋與颱風現況強度動態", "realtime_info"),
    (468, "REAL-TIME INFORMATION", "Typhoon Path", "氣象署官方預估之未來 72 小時颱風暴風圈路徑", "realtime_info"),
    (469, "REAL-TIME INFORMATION", "Radar Information", "即時都卜勒雷達回波圖與降雨雲系發展動態", "realtime_info"),
    (470, "REAL-TIME INFORMATION", "Sunrise / Sunset", "各地當日精確天文日出、日沒與民用曙暮光時刻", "realtime_info"),
    (471, "REAL-TIME INFORMATION", "Moon Phase", "當前月相形態（新月、上弦、滿月、殘月）與月齡", "realtime_info"),
    (472, "REAL-TIME INFORMATION", "Tide Information", "臺灣各主要港口沿海滿潮、乾潮時間與潮差資訊", "realtime_info"),
    (473, "REAL-TIME INFORMATION", "World Time", "紐約、倫敦、東京、雪梨等全球重要都會區當前時間", "realtime_info"),
    (474, "REAL-TIME INFORMATION", "Timezone Conversion", "跨時區會議時間精準換算與日光節約時間計算", "realtime_info"),
    (475, "REAL-TIME INFORMATION", "Current Time", "極致精確之臺灣標準時間 (TST, UTC+8) 即時查詢", "realtime_info"),

    # PRODUCTIVITY (476-495)
    (476, "PRODUCTIVITY", "Todo List", "個人待辦事項清單管理中樞", "productivity"),
    (477, "PRODUCTIVITY", "Personal Tasks", "個人私有工作任務追蹤與劃線標記完成", "productivity"),
    (478, "PRODUCTIVITY", "Guild Tasks", "伺服器公開團隊待辦看板與共同推進專案", "productivity"),
    (479, "PRODUCTIVITY", "Task Priority", "支援緊急、高、中、低四級任務優先權排序", "productivity"),
    (480, "PRODUCTIVITY", "Task Deadline", "為待辦任務設定最後交付截止期限 (Due Date)", "productivity"),
    (481, "PRODUCTIVITY", "Task Reminder", "截止日期前夕自動向指派人發布即將到期提醒", "productivity"),
    (482, "PRODUCTIVITY", "Recurring Tasks", "每日或每週定時自動重複重置之例行性任務", "productivity"),
    (483, "PRODUCTIVITY", "Daily Checklist", "每日固定執行項目打勾清單 (Checklist)", "productivity"),
    (484, "PRODUCTIVITY", "Weekly Checklist", "每週重要常態回顧與維護檢核項目", "productivity"),
    (485, "PRODUCTIVITY", "Progress Tracking", "量化計算專案與清單之百分比完成進度條", "productivity"),
    (486, "PRODUCTIVITY", "Focus Timer", "自訂時長之沉浸專注計時器與免打擾模式", "productivity"),
    (487, "PRODUCTIVITY", "Pomodoro", "經典 25/5 分鐘番茄工作法循環定時器", "productivity"),
    (488, "PRODUCTIVITY", "Countdown Timer", "分秒級即時倒數計時器與 Discord 時間戳", "productivity"),
    (489, "PRODUCTIVITY", "Event Countdown", "針對伺服器重大活動之日數倒數看板", "productivity"),
    (490, "PRODUCTIVITY", "Custom Countdown", "自訂事件名稱與未來日期的專屬倒數器", "productivity"),
    (491, "PRODUCTIVITY", "Habit Tracker", "每日習慣打卡與連續打卡天數 (Streak) 追蹤", "productivity"),
    (492, "PRODUCTIVITY", "Daily Goals", "設定並於每日就寢前檢視之當日核心目標", "productivity"),
    (493, "PRODUCTIVITY", "Weekly Goals", "每週策略目標設定與進度達成率自我審核", "productivity"),
    (494, "PRODUCTIVITY", "Personal Work Log", "記錄個人每日工作產出日誌與復盤省思", "productivity"),
    (495, "PRODUCTIVITY", "Productivity Report", "統計每週專注時間、完成任務數之生產力週報", "productivity"),

    # ENTERTAINMENT / MEDIA (496-500)
    (496, "ENTERTAINMENT / MEDIA", "Trivia Game", "社群常識、科技與二次元益智問答擂台", "games_media"),
    (497, "ENTERTAINMENT / MEDIA", "Guessing Game", "終極密碼、猜數字與單詞猜謎互動小遊戲", "games_media"),
    (498, "ENTERTAINMENT / MEDIA", "Text Adventure", "具備多分支劇情與選擇走向之賽博文字冒險 RPG", "games_media"),
    (499, "ENTERTAINMENT / MEDIA", "Achievement Collection", "在遊戲中解鎖特殊成就並展示於個人檔案", "games_media"),
    (500, "ENTERTAINMENT / MEDIA", "Interactive Mini Game Framework", "高擴充性之互動小遊戲 Session 引擎與分數結算", "games_media"),
]


class MasterFeatureRegistry:
    """ZeroNexus 500 大師特性全域註冊中心。"""

    _features_by_id: Dict[int, MasterFeature] = {}
    _features_by_category: Dict[str, List[MasterFeature]] = {}
    _is_initialized: bool = False

    @classmethod
    def initialize(cls) -> None:
        """初始化並註冊全部 500 項功能。"""
        if cls._is_initialized:
            return

        for fid, cat, name, desc, domain in _RAW_500_FEATURES:
            feature = MasterFeature(
                id=fid,
                category=cat,
                name=name,
                description=desc,
                service_domain=domain
            )
            cls._features_by_id[fid] = feature
            if cat not in cls._features_by_category:
                cls._features_by_category[cat] = []
            cls._features_by_category[cat].append(feature)

        cls._is_initialized = True

    @classmethod
    def get_all(cls) -> List[MasterFeature]:
        cls.initialize()
        return list(cls._features_by_id.values())

    @classmethod
    def get_by_id(cls, feature_id: int) -> Optional[MasterFeature]:
        cls.initialize()
        return cls._features_by_id.get(feature_id)

    @classmethod
    def get_by_category(cls, category: str) -> List[MasterFeature]:
        cls.initialize()
        return cls._features_by_category.get(category, [])

    @classmethod
    def get_categories(cls) -> List[str]:
        cls.initialize()
        return list(cls._features_by_category.keys())

    @classmethod
    def search(cls, keyword: str, limit: int = 10) -> List[MasterFeature]:
        cls.initialize()
        kw = keyword.lower()
        matched = []
        for feat in cls._features_by_id.values():
            if kw in feat.name.lower() or kw in feat.description.lower() or kw in str(feat.id):
                matched.append(feat)
                if len(matched) >= limit:
                    break
        return matched
